### ISSUE TITLE
Update and Check The Breadcrump 

### ISSUE THREAD

**Issue by samuel-vergara-leon** [Azordev/art-marketplace#10]
### Explanation
The breadcrumbs are used so that the user can locate the content that they want to visit on the web page. In this case home, catalog, minimalist and Adrian Olichon. so the user can quickly go to the content they want to see in a quick and concise way.

### Screenshots
![image](https://user-images.githubusercontent.com/97471255/152816930-f56eb7bd-7db1-4e6c-be0f-389deb0fbf72.png)

### Checklist

- [ ] The words home, catalog, minimalist and Adrián Olichon work in the form of buttons

- [ ] Each word frames a specific content

- [ ] breadcrumbs are at the top of page 4

### References
https://www.figma.com/file/zzEwuPfGTiZh4EA11MyZ5c/Sencico?node-id=65%3A51

**Comment by Allislove** [comment]
Done in PR #26
