### ISSUE TITLE
Check Product Information 

### ISSUE THREAD

**Issue by samuel-vergara-leon** [Azordev/art-marketplace#13]
### Explanation 

The name of the name of the artist, and a small description about him is mentioned here, a download button referring to the description of the artist, the specifications, the link and history. This so that the user can obtain information about the artist, his link and any other details.

### Screenshots
![image](https://user-images.githubusercontent.com/97471255/152856391-19835510-6f7c-4d79-aa0f-361d5f17d7ed.png)

### Checklist

- [ ] Each button has a different function
- [ ]  the texts provide information to the user or person who enters the web page and can be found in the specification and history buttons
- [ ] The link button provides the reference of the web page to the user

### References
https://www.figma.com/file/zzEwuPfGTiZh4EA11MyZ5c/Sencico?node-id=65%3A51

**Comment by Katsu08** [comment]
Please specify the changes required in the Checklist. Actually, each button has a different function, the text provides information to the user and the link button provides reference of the web page to the user. 

I propose change the checklist to the changes between the reference page and our page. I want to say: 

example:
- [ ] Description text is now gray #XXXXXX
- [ ] Dropdown menu title text now is blue #XXXXXX
- [ ] Download button is now blue and text white #XXXXXX

**Comment by Allislove** [comment]
I'm  here!

**Comment by Allislove** [comment]
its done in pull request #24
