### ISSUE TITLE
Check Component ProductDetails

### ISSUE THREAD

**Issue by samuel-vergara-leon** [Azordev/art-marketplace#15]
### Explanation
When the user clicks the specifications button found on the product-detail page, the user can read the specifications that exist, in this case concerning the Lorem font. When the user clicks it on, the specification text is cleared below the button, which gives more visual content to the product-detail section.

### Screenshots
<img width="263" alt="image" src="https://user-images.githubusercontent.com/97471255/153002506-02b85cfb-a621-4727-b1f0-665cfd94eabf.png">

### Checklist

- [ ] The spec button has a complementary color code #F8F1F1 with tertiary color letters #11698E.
- [ ] This button has an arrowhead that is located to the right of the word specifications.
- [ ] The word specifications stands out completely from the button, which allows it to be visually striking.

### References
https://www.figma.com/file/zzEwuPfGTiZh4EA11MyZ5c/Sencico?node-id=105%3A645

**Comment by eduardo846** [comment]
Tomado favor verificar

**Comment by Eghinner** [comment]
Can i take it?
