### ISSUE TITLE
Check Home Hero Component

### ISSUE THREAD

**Issue by samuel-vergara-leon** [Azordev/art-marketplace#2]
### Explanation
It is a beautiful large image that is on the right, just below the Navbar component and on its left is a phrase “enter the new world of digital art” and just below this phrase a sign up button.

### Screenshots
![image](https://user-images.githubusercontent.com/97471255/152431908-79df28c3-e4dd-4dfc-9294-f643181345be.png)

### Checklist

- [ ] When the user enters the web page, the aim is to capture the user's attention through an image that stands out and is large.

- [ ] The phrase "among the new world of digital art" is intended to invite the user, either to feel updated or to register. That's exactly why there is a sign up button right next to the sentence.

- [ ] The color of the letters of the phrase “among the new world of digital art” is type black with code #242323, this color makes the phrase stand out even more because its background is white, which gives a more striking due to the black color.

- [ ] The register button is in a slightly darker blue #19456B color, with code letters #FFFFFF and the edges of the button are rounded at the ends.

### References

https://www.figma.com/file/zzEwuPfGTiZh4EA11MyZ5c/Sencico?node-id=65%3A51

**Comment by Eghinner** [comment]
I take this
