### ISSUE TITLE
Implement And Integrate API To The Project

### ISSUE THREAD

**Issue by heliomar-pena** [Azordev/art-marketplace#28]
Currenctly we are using the sencico api, please change the API to another Art API and integrate it with the actual features of the page

- [ ] Actually we have selected this API: https://openaccess-api.clevelandart.org/#appendix-d If you find one better, please comment it
- [ ] The API is getting the images and put it on the homepage and products view
- [ ] The API is used creatively to add a Slider of Categories and filter images
- [ ] The API have a limit and offset (pagination).
- [ ] The download button is working correctly.

**Comment by Israel-Laguan** [comment]
I think we can split this into 2 issues:

1- CRUD-like functions to communicate with new API
2- implementation

This way should be easier.

I suggest this issue will be CRUD-like and to create a new issue for implementing it.
