### ISSUE TITLE
Fix Selected Category Title  Styles In Product View.

### ISSUE THREAD

**Issue by heliomar-pena** [Azordev/art-marketplace#33]
## Explanation:

When the resolution changes to 1024x717, the width of the title does not get 100% of the container div.
The selected category title should have rounded edges to resemble the [figma design](https://www.figma.com/file/zzEwuPfGTiZh4EA11MyZ5c/Sencico?node-id=65%3A51)

## Screenshots

![imagen](https://user-images.githubusercontent.com/66505715/154727341-bd545da9-7b53-4040-8981-46255c464554.png)

## How to reproduce:

1. Enter in this link https://art-marketplace.pages.dev/products?category=26
2. Change the screen size to 1024px width.

## Checklist

- [x] The title of the selected category occupies 100% of the container.
- [x] The border of the title of the selected category is rounded as the design of the figure.

**Comment by manuel040192** [comment]
Quiero tomar esta tarea.

**Comment by manuel040192** [comment]
I'd like to take this task.

**Comment by heliomar-pena** [comment]
Good afternoon!. How did you feel about this task? Have you had any problems solving it? @manuel040192

**Comment by carlosluis911207** [comment]
I want to be assigned to this task
