### ISSUE TITLE
Right And Left Slider Button Is Very Small On Large Screens (1044X827)

### ISSUE THREAD

**Issue by samuel-vergara-leon** [Azordev/art-marketplace#34]
### Explanation.
At a resolution of 1044x827 the button sizes are very small and therefore hardly visible.

### SCREENSHOTS

![](https://static.rock.so/file/eprkZKnw/mAmkQ33j/212a33c8ee67d574d9e04d4943dda43b/t-image.png)

### CHECKLIST 

- [ ] Adjust the buttons size
- [ ] Make the buttons size more visible in a resolution of 1044x827 or higher.
### References.
https://www.figma.com/file/zzEwuPfGTiZh4EA11MyZ5c/Sencico?node-id=105%3A83

**Comment by Eghinner** [comment]
can I take it?

**Comment by Allislove** [comment]
Yesss!

**Comment by heliomar-pena** [comment]
@Eghinner of course!
