### ISSUE TITLE
Change router paths

### ISSUE THREAD

**Issue by heliomar-pena** [Azordev/art-marketplace#36]
### Explanation
Art Marketplace is a portfolio project that uses as a base a real project of one real client, that is the reason why some things remain the same as the other project. As an example of it we have the routes. I have found some routes that refer to products instead of art, for example. I will add a list of routes to change in the checklist, but I would like you to check and let me know if other route looks weird! 

### Screenshots
Say "products" the URL, but this view is not about products else about artworks
![imagen](https://user-images.githubusercontent.com/66505715/155006764-b27ed228-7686-426b-9f14-4cd1735902d5.png)

### Checklist
 Describe the key points to complete the task. This points will help in the pull request test.

 This issue can be closed when the following tasks are completed:
 
 - [ ] `/products/` link has been changed. I think it should be some like `/artworks/` or `/all/`, but I accept suggestions.
 - [ ] `/product/{id}` have been changed. I think should be some like `/artwork/{id}` but I´m open minded, and accept suggestions.
 - [ ] Check if another route exists that can be improved.

**Comment by ygamboalh** [comment]
I want to be assigned to this task.

**Comment by heliomar-pena** [comment]
@Rapsodian You're already assigned, thanks for the help!
