### ISSUE TITLE
Home Group of card Confirmation 

### ISSUE THREAD

**Issue by samuel-vergara-leon** [Azordev/art-marketplace#4]
### Explanation
The user can see a varied group of images where he can choose the one he wants and below there is a download button to keep it on his computer or cell phone.

### Screenshots
![image](https://user-images.githubusercontent.com/97471255/152590692-1ffe5ebe-0301-4f86-9e43-3c664bb4bac1.png)

### Checklist

- [ ] The download button is located just below the creator of the image or photo.

- [ ] The image or in its case photography highlights the owner of it, and is below the image.

- [ ] The download button is a tertiary color code #11698E and the word download is white color code #FFFFFF.

- [ ] The letters where the author's name is highlighted are black with code #000000

### References

https://www.figma.com/file/zzEwuPfGTiZh4EA11MyZ5c/Sencico?node-id=65%3A51

**Comment by Allislove** [comment]
done pr #24 
the cards looks like this  
![Captura de pantalla de 2022-02-14 13-00-47](https://user-images.githubusercontent.com/54194376/153924633-d2b11238-7273-40f5-beb9-3b0ba7dd90ca.png)

**Comment by Israel-Laguan** [comment]
@e-azocar @angelik0828 @Katsu08 please verify if this issue is completed

**Comment by e-azocar** [comment]
> @e-azocar @angelik0828 @Katsu08 please verify if this issue is completed

Ok, I think is solved
