### ISSUE TITLE
Round the login form container borders

### ISSUE THREAD

**Issue by heliomar-pena** [Azordev/art-marketplace#41]
### Explanation
The borders on the box of the login are 0px rounded, but at figma design this has `border-radius: 10px;`.

### Screenshots
![imagen](https://user-images.githubusercontent.com/66505715/155199259-d19e245c-5bc5-487b-9480-85ffa584fbec.png).

### Checklist
 This issue can be closed when the following tasks are completed:
 
 - [ ] Now the box have border-radius: 10px or looks like the design.
 
### References
 - https://www.figma.com/file/zzEwuPfGTiZh4EA11MyZ5c/Sencico?node-id=0%3A1

**Comment by ygamboalh** [comment]
I want to be assigned to this task.
