### ISSUE TITLE
Improve Pagination component

### ISSUE THREAD

**Issue by heliomar-pena** [Azordev/art-marketplace#42]
### Explanation
 The pagination component is presenting some bugs in small screens (check screenshots). I propose three solutions to solve these problems:
 
 - To maintain the logic simply, I propose changing the functionality of the pagination, instead of showing multiple numbers, only show three numbers and the left and right arrows. Some like this: "< 1 **2** 3 >" 
 - To reduce the effort you can use a library.I propose to use [React Paginate](https://www.npmjs.com/package/react-paginate) that looks very similar to our design
 - You can continue working on the component that we have and try to do the functionality shown at the design, this looks like a very difficult work.

### Screenshots
As you see, the pagination is overflow when the screen is small.
![imagen](https://user-images.githubusercontent.com/66505715/155204914-58a12112-761e-4b1c-86d0-5fe5284bead1.png).

Design screenshot
![imagen](https://user-images.githubusercontent.com/66505715/155207297-14ad9ffa-06e6-4958-9bf6-1038e3be38b7.png).

### Checklist
 This issue can be closed when the following tasks are completed:
 
 - [ ] You have chosen one of the three solutions proposed and started to work on it! Please, let me know in the comments what solution you have chosen and the estimation of time that you think this will take for you.
 - [ ] The pagination is working correctly and looks good on small screens. 
 - [ ] It has visual styles similar to the design.
 
### References
- https://www.figma.com/file/zzEwuPfGTiZh4EA11MyZ5c/Sencico?node-id=0%3A1
- https://www.npmjs.com/package/react-paginate

**Comment by Eghinner** [comment]
I'd like to do it
