### ISSUE TITLE
Fix slider arrow position in small screens

### ISSUE THREAD

**Issue by heliomar-pena** [Azordev/art-marketplace#43]
### Explanation
On small screens the slider arrows look unaligned (check screenshots), this slider use the library React Slick, you can check the documentation here: https://react-slick.neostack.com/ . This library allow the use padding and other CSS properties over their parts. To fix this problem please check if something is affecting the arrows and check how you can fix it using CSS and the documentation.

### Screenshots
![imagen](https://user-images.githubusercontent.com/66505715/155206866-cd3a064f-cee3-4c49-b83c-2cdacd82dd97.png)

### Checklist
 This issue can be closed when the following tasks are completed:
 
 - [ ] The arrows are centered in small screens.
 
### References
- https://react-slick.neostack.com/

**Comment by Eghinner** [comment]
I'd like to do it

**Comment by Eghinner** [comment]
This is my suggest. and add "title={item.name}"
![screenshot-localhost_3000-2022 02 22-16_34_35](https://user-images.githubusercontent.com/71513679/155214876-97d39cba-b049-4d01-8ba7-d6811a8945d3.png)
![screenshot-localhost_3000-2022 02 22-16_34_02](https://user-images.githubusercontent.com/71513679/155214910-cc111e7f-7275-4dfa-9836-7eeec7ba2cc0.png)

**Comment by Eghinner** [comment]
if my suggestion works. I think it should have a lower EE.

**Comment by heliomar-pena** [comment]
@Eghinner I think that your pull request #40 have fixed too this issue. What do you think? it is solved?
