### ISSUE TITLE
Home Card Control

### ISSUE THREAD

**Issue by samuel-vergara-leon** [Azordev/art-marketplace#5]
### Explanation
The card is a subcomponent of group card and individually highlights each car.

### Screenshots
![image](https://user-images.githubusercontent.com/97471255/152591651-861d145d-4724-4fca-9e86-f297642d2e9a.png)

### Checklist

- [ ] The download button is located just below the creator of the image or photo.

- [ ]  The letters of the  author's name in this image are highlighted in black with code.

- [ ] The download button is a tertiary color code #11698E and the word download is white color code #FFFFFF.

- [ ]  The letters of the  author's name in this image are highlighted in black with code #000000

### References

https://www.figma.com/file/zzEwuPfGTiZh4EA11MyZ5c/Sencico?node-id=65%3A51

**Comment by Allislove** [comment]
done in pr #24
