### ISSUE TITLE
Updated Designs

### ISSUE THREAD

**Issue by samuel-vergara-leon** [Azordev/art-marketplace#52]
### Explanation:
Latest design from @angelik0828 for this project:

https://www.figma.com/file/zzEwuPfGTiZh4EA11MyZ5c/Sencico?node-id=65%3A51

### Screenshots
<img width="867" alt="image" src="https://user-images.githubusercontent.com/97471255/156373046-65de215a-c1ad-4a9e-964b-36d8f58d8124.png">
 
### References
[sencico.pages.dev](https://sencico.pages.dev/)

**Comment by heliomar-pena** [comment]
Please update the description to be more clear about the reason of this issue
