### ISSUE TITLE
Remove HomeSlider.jsx From The Project.

### ISSUE THREAD

**Issue by heliomar-pena** [Azordev/art-marketplace#54]
### Explanation:

This component is no longer used because we now use a library to handle the sliders. So that it can be removed from the project, keep it clean.

### Checklist
 This issue can be closed when the following tasks are completed:
 
 - [ ] Delete the HomeSlider.jsx file.
 - [ ] Remove HomeSlider.jsx from index.js file.
 - [ ] Delete HomerSlider.test.js

#### Related issues:
 - #55

**Comment by Allislove** [comment]
Done > #64
