### ISSUE TITLE
Delete PartnersSlider From The Project

### ISSUE THREAD

**Issue by heliomar-pena** [Azordev/art-marketplace#55]
### Explanation:
 it´s a very good practice to remove any component that is no longer needed because it keeps code clean and easy to understand.

### Checklist
 This issue can be closed when the following tasks are completed:
 
 - [ ] Delete PartnersSlider.jsx file.
 - [ ] Delete PartnersSlider.jsx file
 - [ ] Delete PartnersSlider.test.js.
 - [ ] Delete PartnersSlider.test.js.

#### Related issues:
 - #54

**Comment by anaceciliamolinares** [comment]
Katsu08, it´s a very good practice to remove any component that is no longer needed because it keeps code clean and easy to understand.

**Comment by Allislove** [comment]
Done > https://github.com/Azordev/art-marketplace/pull/64
