### ISSUE TITLE
Remove CategoriesSlider From The Project

### ISSUE THREAD

**Issue by heliomar-pena** [Azordev/art-marketplace#57]
### Explanation:
 This component is no longer used. So that it can be removed from the project, keep it clean.

### Checklist
 This issue can be closed when the following tasks are completed:
 
 - [ ] Delete the CategoriesSlider.jsx file.

#### Related issues:
 - #54
 - #55

**Comment by arodriguezl9302** [comment]
I feel capable of doing this task
