### ISSUE TITLE
Remove LogosFooter.test.js from the project

### ISSUE THREAD

**Issue by heliomar-pena** [Azordev/art-marketplace#58]
### Explanation:
 These tests are no longer used as the component has been removed. So that it can be removed from the project, keep it clean.

### Checklist
 This issue can be closed when the following tasks are completed:
 
 - [ ] Delete LogosFooter.test.js file.

#### Related issues:
 - #54
 - #55
 - #57

**Comment by Allislove** [comment]
Done > #64
