### ISSUE TITLE
Change "My Downloads" Button To A "My History" Button.

### ISSUE THREAD

**Issue by heliomar-pena** [Azordev/art-marketplace#59]
### Explanation:
In the old layout, when you log in (currently you can log in with any email and password), you can see a "My Downloads" section at the top right.

This functionality is no longer going to be used or doesn't make much sense for the current use of the page, so we thought of creating a "History" style functionality, which saves the last 5 works of art visited.

### Screenshots

You can re-use the actual "My Downloads" menu and modify it visually and functionally to add one history.
![imagen](https://user-images.githubusercontent.com/66505715/156836877-518241ad-e658-48f6-a35a-830fe29d043e.png)

### Checklist
 This issue can be closed when the following tasks are completed:
 
 - [ ] The name now is "My History".
 - [ ] The page is saving the last 5 artworks visited in the localStorage.
 - [ ] The page is showing it in the "My history" section.
 - [ ] The history item have overview information and the image thumbnail.
 - [ ] When you click in some history item, you're redirected to the art page.

**Comment by Allislove** [comment]
this issue can be EE5!!

**Comment by heliomar-pena** [comment]
Hello @Allislove, how you go with this issue? Do you think you want to complete it or it can be assigned to another person?
