### ISSUE TITLE
Visual Footer Component Confirmation

### ISSUE THREAD

**Issue by samuel-vergara-leon** [Azordev/art-marketplace#6]
### Explanation
It is located at the end of the page and seeks to provide the user with valuable information regarding  Azordev company.  For example, it contains the mission, the legal situation, the history, and etc.
The user can also find the login and register buttons, this with the purpose that if the person has not registered or has not logged in yet.

### Screenshots
![image](https://user-images.githubusercontent.com/97471255/152593120-acfdde65-a9af-468d-9ee0-bf502c5ac13a.png)

### Checklist

- [ ]  Azordev company logo is highlighted on the left side of the footer.

- [ ] There is a variety  of information about the company, such as legality, which is one of the issues of mistrust in any other web page.

- [ ] There are two sections. The first one  deals with the information on the page and the second one is about who we are (Azordev).

- [ ] The login button is in a slightly dark blue #19456B color, with code letters #FFFFFF and the edges of the button are rounded at their tips.

- [ ] The sign up button is in a tertiary color code #11698E , with code letters #FFFFFF and the button edges are rounded at the ends.

### Step by step reproduction steps for the issue

- Open the app
- In any page scroll down to the bottom
- Verify the footer is different that in design 

### References

https://www.figma.com/file/zzEwuPfGTiZh4EA11MyZ5c/Sencico?node-id=65%3Aa

**Comment by Allislove** [comment]
Done in PR #25

**Comment by Allislove** [comment]
@e-azocar  Can you review please!
