### ISSUE TITLE
 Footer Buttons Look Poorly Positioned.

### ISSUE THREAD

**Issue by heliomar-pena** [Azordev/art-marketplace#66]
**Describe The Bug**
When I scrolled down to the art market footer, I noticed that the buttons look weird, "Login" is right-aligned and "Sign Up" is left-aligned. I feel this is not friendly to the user.

**To Reproduce**
1. Go to art-marketplace.pages.dev/.
2. Scroll down to footer.

**Expected Behavior**
The behavior is expected to be as shown in [figma].
(https://www.figma.com/file/zzEwuPfGTiZh4EA11MyZ5c/Sencico?node-id=65%3A2), por favor revise en el apartado de imágenes

**Screenshots**
![imagen](https://user-images.githubusercontent.com/66505715/157519687-08348b7e-c6b3-4be1-8e53-5e9aab1a9aff.png)

**Comment by arodriguezl9302** [comment]
I would like to do this task
