### ISSUE TITLE
Update clickable link/buttons style

### ISSUE THREAD

**Issue by Israel-Laguan** [Azordev/art-marketplace#70]
Visually some elements are not clear about purpose, for example 
![image](https://user-images.githubusercontent.com/36519478/157878499-752b57ba-7fc4-41a2-88bb-8e2a0a2c7705.png)

Its meant to be clickable, and to send you to the filterable list of artworks, but visually is not clear enough it is mean t to be clickable

Maybe add underline? Or convert to a button?

**Describe alternatives you've considered**
Add a tooltip is another solution but is not viable for mobile.

**Additional context**
This is important because UI should be easy to use, but now yu have to know the system

**Comment by Israel-Laguan** [comment]
@samuel-vergara-leon

**Comment by arodriguezl9302** [comment]
I want to be assigned to this task
