### ISSUE TITLE
Update metatags for social sharing

### ISSUE THREAD

**Issue by Israel-Laguan** [Azordev/art-marketplace#71]
If we try to share the link of this site, the experience is far from ideal

![image](https://user-images.githubusercontent.com/36519478/157879270-fe3317ab-6fd9-4389-99f1-b9615e3b2a36.png)

Notice it don't have image, nor description.

**Describe the solution you'd like**
Just add and improve metatags on the `/public/index.html`

**Describe alternatives you've considered**
Using a react package, but can be overkill

**Additional context**
As this project is meant to be showcase, is poor experience to leave like it is

**Comment by Israel-Laguan** [comment]
@samuel-vergara-leon

**Comment by heliomar-pena** [comment]
Help me please to add E.E for this task @Israel-Laguan @e-azocar , I don't was added these metatags before.
