### ISSUE TITLE
  Add Dropdown Next To Search Bar

### ISSUE THREAD

**Issue by Ricardo-Gomez1** [Azordev/art-marketplace#79]
Explanation:

Observing such an extensive navigation menu in a carousel format on the home page generates a bad user experience and complicates navigation on the page, as well as its location, which should be at the top next to the search bar with a menu of burgers. style, in the following example of Falabella I propose to put the categories or Departments on the left side and the types of art found in each of them on the right side.

**Url home:**
https://art-marketplace.pages.dev/

Describe the solution you would like.
As a UX improvement, a dropdown menu should be provided with the categories next to the search bar and with groups that do not make the categories so extensive.

Current carousel menu to change:

![image](https://user-images.githubusercontent.com/101886534/160916371-351b4979-6d98-4e7d-afc6-3f2003cf2840.png)

New Burger Menu Location:

![image](https://user-images.githubusercontent.com/101886534/160916520-499df265-248e-47f1-a06e-7ee318216e37.png)

Example burger menu:

![image](https://user-images.githubusercontent.com/101886534/160009528-ee1d4d8f-c040-42c7-8bfa-355e23b75a05.png)

**Comment by Israel-Laguan** [comment]
@angelik0828 what do you think of this proposal?

**Comment by Israel-Laguan** [comment]
I think this is not feasible as design will change
