### ISSUE TITLE
Check Visual Title

### ISSUE THREAD

**Issue by samuel-vergara-leon** [Azordev/art-marketplace#8]
### Explanation

The title component is closely related to the filter, since the title reflects the option that was taken in the filter and returns a list of images depending on the option  chosen. In other words, the title is not partial and is subject to the filter exclusively here . In this case the color of the button is blue and its letters and words vary according to the filter.

### Screenshots
![image](https://user-images.githubusercontent.com/97471255/152813029-8ebe5de4-f5b3-474a-84f1-a7e59a6d5c34.png)

### Checklist

- [ ] The titles change according to the option that is chosen in filter.
- [ ] The color of the letter in the title does not change, it remains stable.
- [ ] The images obey the inscribed title, that is, they are in accordance with the chosen option in filter

### References
https://www.figma.com/file/zzEwuPfGTiZh4EA11MyZ5c/Sencico?node-id=65%3A51

**Comment by Eghinner** [comment]
Can take this?
