### ISSUE TITLE
  Develop Carousel For Main Home Banner  

### ISSUE THREAD

**Issue by Ricardo-Gomez1** [Azordev/art-marketplace#80]
Explanation:

The main banner of the home must be attractive and show the most relevant information or that you want to communicate with certain campaigns that are running in an e-commerce, so the current banner is wasted and does not invite users to browse . 

Describe the solution you would like.
Develop a carousel with around 4 boxes showing the most important features and the most relevant jobs.

Describe alternatives you have considered.
Create a carousel module at the top of the home page, which is where you'll see most of the navigation and hot spots.

Additional context:
Create the carousel in the space shown in the following image.
![image](https://user-images.githubusercontent.com/101886534/160031341-4363e876-5b2b-4225-9a97-b645d76a904b.png)

**Comment by Israel-Laguan** [comment]
I think this is not feasible as design will change
