### ISSUE TITLE
 Display Pop Up For Login

### ISSUE THREAD

**Issue by Ricardo-Gomez1** [Azordev/art-marketplace#81]
Is your feature request related to a problem? Please describe.
Clicking on the login CTA directs the user to a new screen, which in UX is not good.

Describe the solution you would like.
Display a Pop Up keeping the user in the home with the fields required to log in.

Additional context:
I share a video of what the pop up and its creation would look like:
https://www.youtube.com/watch?v=TXgjDxBzqoI

**Comment by heliomar-pena** [comment]
Example by @angelik0828 : 

![image](https://user-images.githubusercontent.com/66505715/160945249-4a079c1b-05e4-49ee-aa2e-3f263828f1b0.png)

**Comment by Israel-Laguan** [comment]
I think this is not feasible as the design will change
