### ISSUE TITLE
    Rearrange Registry View.

### ISSUE THREAD

**Issue by Ricardo-Gomez1** [Azordev/art-marketplace#83]
Explanation:

Is your feature request related to a problem? Please describe.
The copies on the screen of the registration form are not clear and generate a bad experience for the user since they can lead to confusion, additionally it should be clarified which fields are mandatory within the form in order to guide the user and as a good practice for the CRM.

Describe the solution you would like.
Change the title of the account details form to Registration, remove the personal information subtitle, and clarify with a * which fields are required within the form.

Describe alternatives you have considered.
Attached image of fields to correct.

![image](https://user-images.githubusercontent.com/101886534/161060307-f045ab42-9cea-4e56-ac26-3b2810f9a72e.png)

**Comment by Israel-Laguan** [comment]
I think this is not feasible as the design will change
