### ISSUE TITLE
   Change The Fields Of The Registration Form

### ISSUE THREAD

**Issue by Ricardo-Gomez1** [Azordev/art-marketplace#84]
**Is your feature request related to a problem? Please describe.**
The information requested from customers must add value to the company's marketing strategy, being clear about this the fields that are observed in the registration form are not clear and also the company's privacy policies are not being shown and likewise The client is not being shown authorization to receive advertising communications that can be generated from the company's customer loyalty area with targeted campaigns.

**Describe the solution you would like**
Make changes in the fields requested by the client, including the fields necessary for the construction of the company's CRM.
- Eliminate company and occupation for more relevant data such as gender, date of birth, change of copy from phone to cell.
- Change the fields of the registration form.
- Display policies for data manipulation.
- Opt to receive advertising messages.

**Describe the alternatives you have considered**

 **Registration Screen URL:**

https://art-marketplace.pages.dev/register

**Attached screen of changes to be made.**

![image](https://user-images.githubusercontent.com/101886534/161059336-5b4cc0b3-20b9-4b88-b801-4cf31f6d88a3.png)

**Comment by Israel-Laguan** [comment]
I think this is not feasible as the design will change
