### ISSUE TITLE
Styles In The Categories Section

### ISSUE THREAD

**Issue by angelik0828** [Azordev/art-marketplace#86]
### Explanation:

In [Artworks](https://art-marketplace.pages.dev/artworks/), when searching by filters, we have two lists: one of categories and another of types, a visual indication must be added to highlight which of the list items are currently selected.

### Screenshots:
Currently:
![image](https://user-images.githubusercontent.com/4030477/161819149-090b8f09-d138-4d9b-a3d2-6b2cce9684b2.png)

Should be:
![image](https://user-images.githubusercontent.com/4030477/161819304-4a8bfc0f-cc1c-4d37-b957-da8bfd03199c.png)

### Checklist

 - [x] Remove underline in categories items
 - [x] Add background when some category is selected and change color to white
 - [x] Create and implement active state for the active item at filter list.
 
### References:
https://www.figma.com/file/zzEwuPfGTiZh4EA11MyZ5c/Sencico?node-id=65%3A2

**Comment by anaceciliamolinares** [comment]
I strongly recommend that the issues be better written in Spanish for greater effectiveness both  in understanding as well as the easy interpretation of them.

**Comment by arodriguezl9302** [comment]
I would like to be assigned to this task @Katsu08 @e-azocar @Israel-Laguan

**Comment by heliomar-pena** [comment]
you're assigned now @arodriguezl9302
