### ISSUE TITLE
Add clear button in Search Bar

### ISSUE THREAD

**Issue by angelik0828** [Azordev/art-marketplace#87]
Explanation:

When doing a search, and realize the changing the search has no tool that allows you to delete the field and perform a new search, you want this tool to be implemented.

### Screenshots:

![image](https://user-images.githubusercontent.com/4030477/161828250-4d31eb0d-92ec-4cd2-bd50-d3961f21b13e.png)
![image](https://user-images.githubusercontent.com/66505715/162049616-4ea558b0-68dc-48c2-b9de-a0f67872288b.png)

Checklist:
 
 - [ ] Place X in the search text field.
 - [ ] Icon have some padding to be clickeable
 - [ ] Check that the responsive looks good.
 - [ ] Pressing the X button on the search would clear the search bar and perform the query with the empty text search.
 
References:

https://www.figma.com/file/zzEwuPfGTiZh4EA11MyZ5c/Sencico?node-id=65%3A2

**Comment by arodriguezl9302** [comment]
I would like to be assigned to this task @Katsu08 @e-azocar @Israel-Laguan
