### ISSUE TITLE
Change Visual Pager 

### ISSUE THREAD

**Issue by samuel-vergara-leon** [Azordev/art-marketplace#9]
### Explanation
It is located on the second page of Art Marketplace, and its function is to indicate which page the user is on, so that the number of the page where the user is located stands out more than the others, it also has  previous buttons on opposite sides and next. This to go back or forward, it can be page by page or go directly to a specific page using the page numbers.

### Screenshots
![image](https://user-images.githubusercontent.com/97471255/152814692-63d80447-e8c5-43ec-b730-eeb024a0100c.png)

### Checklist

- [ ] The pager is made up of "numbers", "next" and "previous" words.

- [ ] Each button redirects you to a specific page.

- [ ] The user can go directly to the desired page quickly by the specific number.  

### References
https://www.figma.com/file/zzEwuPfGTiZh4EA11MyZ5c/Sencico?node-id=65%3A51

**Comment by Eghinner** [comment]
Can i take this task?
