### ISSUE TITLE
Remove Logo And Center Footer On Mobile Login Page   /  Eliminar Logo Y Centrar El Pie De Página En La Pagina De Inicio De Sesión Mobile  

### ISSUE THREAD

**Issue by Ricardo-Gomez1** [Azordev/art-marketplace#92]
** Explanation:**

In the footer of the login screen you can see the Azordev logo and just below it you can see the "about us and home page" sections in a messy way, said logo does not need to be there, since it is located in the upper left corner.

** Current result:** The name of the sections looks disorganized with respect to the Azordev logo.

**Expected Result:** Remove the Azordev logo and center the About Us and Home Page sections

*Screen size:*: Mobile version

Screenshots:

![image](https://user-images.githubusercontent.com/101886534/169721977-68465ce3-ad88-45b6-a72c-4f166359b29d.png)
![image](https://user-images.githubusercontent.com/101886534/169722052-11f8b91a-e988-49cf-a492-0c862742b71d.png)

Check list:
The tasks to be carried out are the following:

- [ ] Delete the lower Azordev logo in the footer of the Mobile version
- [ ] Center the about us and main page sections in the footer of the Mobile version

### References:
https://art-marketplace.pages.dev/login

-----------------------------------------------------------------

**Spanish Version**

** Explicación:**

En el pie de página de la pantalla de inicio de sesión se observa el logo de Azordev y justo debajo se ven las secciones de "sobre nosotros y página principal" de una manera desordenada, dicho logo no hace falta que este allí, ya que se encuentra en la esquina superior izquierda.

** Resultado actual:** El nombre de las secciones se ve desorganizado con respecto al logo de Azordev.

**Resultado esperado:** Eliminar el logo de Azordev y centrar las secciones de Sobre nosotros y página principal

*Tamaño de pantalla:*: 
Versión Mobile

**Capturas de pantalla:
![image](https://user-images.githubusercontent.com/101886534/169721977-68465ce3-ad88-45b6-a72c-4f166359b29d.png)
![image](https://user-images.githubusercontent.com/101886534/169722052-11f8b91a-e988-49cf-a492-0c862742b71d.png)

Lista de verificación:
Las tareas a realizar son las siguientes:

- [ ] Eliminar el logo inferior de Azordev en el pie de página de la versión Mobile.
- [ ] Centrar las secciones de sobre nosotros y página principal en el pie de página de la versión Mobile.

### Referencias:

https://art-marketplace.pages.dev/login

**Comment by Israel-Laguan** [comment]
I think this is not feasible as the design will change
