### ISSUE TITLE
Create Additional Screen To Footer Links   /  Crear Pantalla Adicional A Los Enlaces Del Pie De Página 

### ISSUE THREAD

**Issue by Ricardo-Gomez1** [Azordev/art-marketplace#93]
**Explanation:**

Although it is a project for the Brief of the company, a generic screen should be designed to which it takes to click on the links in the footer and not redirect it to the start again.

**Actual result:** There is no screen to direct users to footer links.

**Expected result:** Design a generic screen that takes users to click on the footer sections.

*Screen size:* All versions.
**Screenshots:**

![image](https://user-images.githubusercontent.com/101886534/169878537-d1fac1dc-5b80-4577-88d3-5901aaebd98e.png)
**Check list:**

The tasks for the issue are as follows:

- [ ] Build the design of a screen where users are directed when they click on the links in the footer

- [ ] Correct the CTA of the links to this new screen
** References:**

https://art-marketplace.pages.dev/#

-----------------------------------------------------------------

**Spanish Version**

Aunque es un proyecto para el Brief o Manual de marca  de la empresa, se debe diseñar una pantalla genérica a la cual se lleve darle clic a los enlaces del pie de página y no redirigirlo al inicio de nuevo.

**Resultado actual:** No se tiene una pantalla para dirigir a los usuarios en los enlaces del pie de página.

**Resultados esperados:** Diseñar una pantalla genérica que lleve a los usuarios al darle clic en las secciones del pie de página.

*Tamaño de la pantalla:*  Todas las versiones.
**Capturas de pantalla:**

![image](https://user-images.githubusercontent.com/101886534/169878537-d1fac1dc-5b80-4577-88d3-5901aaebd98e.png)
**Lista de verificación:**

Las tareas para la issue son las siguientes:

- [ ]  Construir el diseño de una pantalla a donde se dirijan a los usuarios al darle clic a los enlaces del pie de página.

- [ ]  Corregir el CTA de los enlaces a esta nueva pantalla
** Referencias:**
https://art-marketplace.pages.dev/#

**Comment by angelik0828** [comment]
We could think about the construction of some pages for that information, that would be separate and in more detail than it should go.

**Comment by Israel-Laguan** [comment]
I think this is not feasible as the design will change
