### ISSUE TITLE
Create An Action To Magnifying Glass Search Bar  /   Crear Una Acción A La Lupa De La Barra De Búsqueda 

### ISSUE THREAD

**Issue by Ricardo-Gomez1** [Azordev/art-marketplace#94]
### Explanation:

To have a good user experience in the search bar, it is advisable to create a CTA (Call to Action Button) with a search magnifying glass to make it easy for customers to navigate.

**Actual result:** The magnifying glass does not generate a search when clicked.

**Expected Result:** Clicking on the magnifying glass should work as an input.

*Screen size:* All versions.

### Screenshots:
![image](https://user-images.githubusercontent.com/101886534/169880993-69560a1e-a57f-4215-a660-4e6e932a1a8f.png)
 Check list:

To complete the problem, the following must be done:

- [ ] Create a CTA (Call to Action Button) that is the same as pressing Enter from the keyboard for desktop and mobile.

###References:
https://art-marketplace.pages.dev/#

-----------------------------------------------------------------

**Spanish Version**

Para tener una buena experiencia de usuario en la barra de búsqueda, es aconsejable crear a CTA (Call to Action Button)  con lupa de búsqueda para generar facilidad de navegación a los clientes.

**Resultado real:** La lupa no genera una búsqueda cuando se hace clic.

**Resultado esperado:** Que al hacer clic en la lupa debería funcionar como una entrada.

*Tamaño de pantalla:* Todas las versiones.

### Capturas de pantalla:

![imagen](https://user-images.githubusercontent.com/101886534/169880993-69560a1e-a57f-4215-a660-4e6e932a1a8f.png)
 Lista de Verificación:

Para completar el problema, se debe hacer lo siguiente:

- [ ] Crear a CTA (Call to Action Button) que sea lo mismo que presionar Intro desde el teclado para las versiones de escritorio y móvil.

###Referencias:
https://art-marketplace.pages.dev/#

**Comment by Coolhatena** [comment]
Done! I already created the pull request with the solution

**Comment by angelik0828** [comment]
![image](https://user-images.githubusercontent.com/4030477/174401390-8e669d71-3787-4409-95cf-17272f65f100.png)
