### ISSUE TITLE
Generate Predictive Texts In The Search Bar To Give Options To The User  /  Crear Textos Predictivos En La Barra de Búsqueda Para Dar Opciones Al Usuario   

### ISSUE THREAD

**Issue by Ricardo-Gomez1** [Azordev/art-marketplace#95]
### Explanation:

Generating predictive text with the first 3 letters in the search bar will give users a better UX and give a bigger picture of what they can find on the page. As an example attached to the Falabella retailer.

![image](https://user-images.githubusercontent.com/101886534/169882142-c79c6701-251b-4111-ae75-47eea6cd6b56.png)

**Actual Result:** No prediction is generated for users' search help in the search bar.

**Expected result:** By typing the first 3 letters in the search bar, some predictive texts should be generated for the user's search.

*Screen size:* All versions

### Screenshots:
![image](https://user-images.githubusercontent.com/101886534/169882641-3faec124-7123-4ce3-94f4-6e648df1259c.png)

### Check list:
To complete the topic you must:

- [ ] Carry out development that allows making predictions of what the user is going to look for in the search bar when typing the first 3 letters of his search.

###References:

https://art-marketplace.pages.dev/#

-----------------------------------------------------------------

**Spanish Version**

### Explicación:

Generar un texto predictivo con las primeras 3 letras en la barra de búsqueda, brindará a los usuarios una mejor UX y brindará una imagen más amplia de lo que pueden encontrar en la página.  Como un ejemplo adjunto al minorista de Falabella.

![imagen](https://user-images.githubusercontent.com/101886534/169882142-c79c6701-251b-4111-ae75-47eea6cd6b56.png)

**Resultado real:** No se genera predicción para la ayuda en la búsqueda de los usuarios en la barra de búsqueda.

**Resultado esperado:** Al escribir las 3 primeras  letras en la barra de búsqueda, se deberían generar unos textos predictivos para la búsqueda del usuario.

*Tamaño de pantalla:* Todas las versiones

### Capturas de pantalla:

![imagen](https://user-images.githubusercontent.com/101886534/169882641-3faec124-7123-4ce3-94f4-6e648df1259c.png)

### Lista de Verificación:

Para completar el tema debe ejecutar las siguientes acciones:

- [ ] Realizar desarrollo que permita hacer predicciones de lo que el usuario va a buscar en la barra de búsqueda al digitar las 3 primeras letras de su búsqueda.

###Referencias:
https://art-marketplace.pages.dev/#

**Comment by e-azocar** [comment]
We would need a design to do it

**Comment by Israel-Laguan** [comment]
I think this is not feasible as the design will change
