### ISSUE TITLE
Create A Slider On Categories For Mobile Version  /  Crear Un Control Deslizante En Categorías Para La Versión Móvil  

### ISSUE THREAD

**Issue by Ricardo-Gomez1** [Azordev/art-marketplace#96]
### Explanation:

To see the entire house from a mobile device, a lot of scrolling or sliding must be done and this generates an unnecessary distraction for the user, so it does not reach the final sections of the house, thus generating a bad user experience.

**Actual result:** There is a very long start to user navigation from the mobile version.

**Expected Result:** Generate a shorter and more user-friendly house by means of a slider.

**Image example:**
![image](https://user-images.githubusercontent.com/101886534/169887715-d1af9a39-f010-4b89-a1a3-fa16d5af6c70.png)

*Screen size:* Mobile version.

### Screenshots:
Current view where you can see how they have to scroll or slide:

![image](https://user-images.githubusercontent.com/101886534/169886590-95e6126b-06b4-4160-9f7e-49fea0cfbb5e.png)
![image](https://user-images.githubusercontent.com/101886534/169886651-0b27a283-2171-41e2-8d3b-87e29fa3d2ef.png)

### Check list:
To complete the topic you must do the following:

- [ ] Build by category. (Art by female artists, on display, new works), a slider with the first 3 works and one more to soften the experience.

###References:
https://art-marketplace.pages.dev/

-----------------------------------------------------------------

**Spanish Version**

### Explicación:

Para ver toda la casa desde un dispositivo móvil se debe hacer mucho scroll o deslizamiento y esto genera una distracción innecesaria al usuario, por lo que no llega a las secciones finales de la casa, generando así una mala experiencia de usuario.

**Resultado real:** Hay un comienzo muy largo para la navegación del usuario desde la versión móvil.

**Resultado esperado:** Generar una casa más corta y fácil de usar por medio de un control deslizante.

**Ejemplo de imagen:**

![imagen](https://user-images.githubusercontent.com/101886534/169887715-d1af9a39-f010-4b89-a1a3-fa16d5af6c70.png)

*Tamaño de pantalla:* Versión móvil.

### Capturas de pantalla:
Vista actual donde se puede ver cómo se tienen que desplazar o deslizar:

![imagen](https://user-images.githubusercontent.com/101886534/169886590-95e6126b-06b4-4160-9f7e-49fea0cfbb5e.png)
![imagen](https://user-images.githubusercontent.com/101886534/169886651-0b27a283-2171-41e2-8d3b-87e29fa3d2ef.png)

### Lista de Verificación:
Para completar el tema debes hacer lo siguiente:

- [ ] Construir por categoría. (Arte de artistas femeninas, en exhibición, obras nuevas), un slider con las 3 primeras obras y una más para suavizar la experiencia.

###Referencias:
https://art-marketplace.pages.dev/

**Comment by e-azocar** [comment]
I think would be hard add a slider only for mobile view

**Comment by angelik0828** [comment]
@Ricardo-Gomez1 What other item could we use?

**Comment by hector-trompis** [comment]
Cual es la EE de esta issues?

**Comment by Israel-Laguan** [comment]
I think this is not feasible as the design will change
