### ISSUE TITLE
Icon In Mobile View Very Close To Top Margin /  Icono En Vista Móvil Muy Cerca Del Margen Superior

### ISSUE THREAD

**Issue by angelik0828** [Azordev/art-marketplace#97]
### Explanation:

When entering mobile view, the icon looks very close to the top, this should be in proportion to the space under the icon there.

**Actual result:** There is no space between the application icon, and the top margin.

**Expected result:** That the application icon is at a reasonable distance from the top margin.

*Screen size:*  320X538, 375X538, 425X538, 768X538,

### Screenshots;
![image](https://user-images.githubusercontent.com/4030477/170735056-d823dc9e-3235-4076-9de0-fbe135b24bd0.png)
![image](https://user-images.githubusercontent.com/4030477/170735084-93dfe066-b6ed-4874-b65b-0c6674f7dcdd.png)
![image](https://user-images.githubusercontent.com/4030477/170735125-3d05bc0c-8a71-4bd3-8036-00b557c8f740.png)
![image](https://user-images.githubusercontent.com/4030477/170735158-02d502f4-4868-40d6-922f-561d82500f83.png)

### Checklist:
 
 - [ ] The icon must be at a distance from the top margin that is proportional to the bottom margin.
 
### References:
https://art-marketplace.pages.dev/

-----------------------------------------------------------------

**Spanish Version**

### Explicación:

Al ingresar a la vista móvil, el ícono se ve muy cerca de la parte superior, esto debe ser proporcional al espacio debajo del ícono allí.

**Resultado real:** No hay espacio entre el ícono de la aplicación y el margen superior.

**Resultado esperado:** Que el ícono de la aplicación esté a una distancia razonable del margen superior.

*Tamaño de pantalla:* 320X538, 375X538, 425X538, 768X538,

### Capturas de pantalla:
![imagen](https://user-images.githubusercontent.com/4030477/170735056-d823dc9e-3235-4076-9de0-fbe135b24bd0.png)
![imagen](https://user-images.githubusercontent.com/4030477/170735084-93dfe066-b6ed-4874-b65b-0c6674f7dcdd.png)
![imagen](https://user-images.githubusercontent.com/4030477/170735125-3d05bc0c-8a71-4bd3-8036-00b557c8f740.png)
![imagen](https://user-images.githubusercontent.com/4030477/170735158-02d502f4-4868-40d6-922f-561d82500f83.png)

### Lista de Verificación:
- [ ] El ícono debe estar a una distancia del margen superior que sea proporcional al margen inferior.

### Referencias:
https://art-marketplace.pages.dev/

**Comment by Israel-Laguan** [comment]
I think this is not feasible as the design will change
