### ISSUE TITLE
Header Does Not Disappear When Scrolling  /  El Encabezado No Desaparece Al Desplazarse

### ISSUE THREAD

**Issue by angelik0828** [Azordev/art-marketplace#98]
### Explanation:

The header in the mobile view for tablet does not disappear when scrolling like in the smaller views.

**Actual result:** 
Header doesn't disappear when scrolling in tablet view.

**Expected result:** That when entering scrolling, the menu disappears.

*Screen size:*  (768X538)

### Screenshots:
![image](https://user-images.githubusercontent.com/4030477/170736824-98cf8d63-d8e4-45b9-bae5-1bb6eb3e0a07.png)

### Checklist:
- [ ] That when entering and scrolling or moving, the menu disappears.
 
### References:
 https://art-marketplace.pages.dev/

-----------------------------------------------------------------

**Spanish Version**

### Explicación:

El encabezado en la vista móvil para tableta no desaparece cuando se desplaza como en las vistas más pequeñas.

**Resultado actual:**
El encabezado no desaparece al desplazarse en la vista de tableta.

**Resultado esperado:** Que al entrar en scroll desaparezca el menú.

*Tamaño de pantalla:* (768X538)

### Capturas de pantalla:
![imagen](https://user-images.githubusercontent.com/4030477/170736824-98cf8d63-d8e4-45b9-bae5-1bb6eb3e0a07.png)

### Lista de Verificación:
- [ ] Que al entrar y desplazarse o dar scroll, el menú desaparezca.

### Referencias:
https://art-marketplace.pages.dev/

**Comment by angelik0828** [comment]
@e-azocar @hector-trompis @Israel-Laguan, I think that this task should be done because it will give us problems in the application even if it is changed from UX.

**Comment by e-azocar** [comment]
@angelik0828 I can do it

**Comment by angelik0828** [comment]
Reviewed is perfect thank you very much!! @e-azocar
